CREATE TABLE STUDENT1(
	SNO NUMBER(3) CONSTRAINTS PKSNO PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	COURSE VARCHAR2(10) DEFAULT 'BCA'
);

CREATE TABLE FEES2(
	SNO NUMBER(3),
	AMOUNT NUMBER(3),
	FEESDATE DATE
);

 